package controller.connection.command;

public enum CommandName {
    GET_2_PL_MATCH_COMMAND,
    GET_2_PL_MATCH_COMMAND2,
    GET_2_PL_MATCH_COMMAND3,
    GET_2_PL_MATCH_COMMAND4,
    GET_2_PL_MATCH_COMMAND5,
    GET_2_PL_MATCH_COMMAND6,
    GET_PL_MATCH_COMMAND,
    GET_PL_MATCH2_COMMAND,
    GET_PL_MATCH3_COMMAND,
    GET_PL_MATCH4_COMMAND,
    GET_PLAYER_LIST_COMMAND,
    GET_LEAGUE_LIST_COMMAND,
    GET_ACCESS_COMMAND,
    GET_LAST_MATCH_DATE_COMMAND,
    GET_USER_LIST_COMMAND,
    LOAD_PREV_DATA_COMMAND,
    WRITE_UNREGISTERED_USER

}
